Adding info about the fiveg_n4 interface
canonical/charm-relation-interfaces pull request #102
Opened 2023-09-12 10:02 UTC by Gmerold

**Overview:**
In 5G Core, the `N4` interface is used to establish a bridge between the User Plane and the Control Plane. 
A new charm relation interface facilitates connectivity over the N4 interface, between the interface provider and requirer.

**Reference:**
https://docs.google.com/document/d/1s3U82GTUZFJ9mEhiHig0oAl44F0fq3eQT2PNv1uV75g/edit

2023-09-12 13:15 UTC, ghislainbourgeois requested changes

2023-09-12 13:15 UTC, ghislainbourgeois commented on interfaces/fiveg_n4/v0/README.md
> +In a typical 5G network, the N4 interface is used between UPF and AMF.
In our specific case, this relation will not be consumed directly by the SMF, but probably by the new NMS to allow it to be configured in a network slice. I am not sure if we want to add a note on that.

2023-09-12 13:22 UTC, gruyaume approved these changes
LGTM besides @ghislainbourgeois 's comments

2023-09-13 12:02 UTC, DanielArndt commented on interfaces/fiveg_n4/v0/schema.py
> +"""
```suggestion
"""This file defines the schemas for the provider and requirer sides of the `fiveg_n4` interface.

It exposes two `interfaces.schema_base.DataBagSchema` subclasses called:
- `ProviderSchema`
- `RequirerSchema`

Examples:

    ProviderSchema:
        unit: <empty>
        app: {
            "upf_hostname": "upf.uplane-cloud.canonical.com",
            "upf_port": 8805
        }

    RequirerSchema:
        unit: <empty>
        app:  <empty>
"""
```

2023-09-13 13:10 UTC, Gmerold commented on interfaces/fiveg_n4/v0/README.md
> +- Is expected to provide the hostname and the port of the UPF's N4 interface.
The protocol for the N4 interface is specified by 3GPP, so I figured we don't have mention it here.

2023-09-13 15:35 UTC, patriciareinoso commented on interfaces/fiveg_n4/v0/schema.py
> +from pydantic import BaseModel, IPvAnyAddress, Field
```suggestion
from pydantic import BaseModel, Field
```

2023-09-14 18:07 UTC, ghislainbourgeois commented on interfaces/fiveg_n4/v0/README.md
> +In a typical 5G network, the N4 interface is used between UPF and AMF.
I agree that mentioning the NMS is a bit too specific to this one implementation. I think the wording here is fine.

2023-09-14 18:08 UTC, ghislainbourgeois approved these changes

2023-09-15 12:48 UTC, simskij approved these changes

2023-09-15 12:48 UTC, merged