feat: Adding sdcore-config interface
canonical/charm-relation-interfaces pull request #146
Opened 2024-04-17 09:42 UTC by gatici

Adding sdcore-config interface which is used to provide Webui GRPC address (Webui hostname + GRPC port)  to 5G control plane NF's.

2024-04-17 13:19 UTC, ghislainbourgeois requested changes

2024-04-17 14:54 UTC, gatici commented on docs/json_schemas/dns_record/v0/requirer.json
> +      ],
This is done automatically when we run `tox -e build-json-schemas`.  I will revert it.

2024-04-17 15:00 UTC, gatici commented on interfaces/sdcore_config/v0/README.md
> +Within 5G, the Webui URL needs to be known by other components as SD-Core Webui Operator is responsible for the configuration of the SD-Core network.
Done

2024-04-17 15:00 UTC, gatici commented on interfaces/sdcore_config/v0/README.md
> +Hence, 5G NF's need to connect to config server using Webui URL which is consist of Webui Operator hostname which equals to application name and a fixed GRPC port.
Done

2024-04-17 17:18 UTC, ghislainbourgeois commented on docs/json_schemas/dns_record/v0/requirer.json
> +      ],
Ok, understood.

2024-04-17 17:18 UTC, ghislainbourgeois approved these changes

2024-04-17 17:25 UTC, markbeierl approved these changes

2024-04-18 04:38 UTC, tonyandrewmeyer reviewed
This could probably get added to the Telco table in the top-level README, I think? Presumably with draft since there aren't tests yet.

2024-04-18 10:42 UTC, gatici commented
> This could probably get added to the Telco table in the top-level README, I think? Presumably with draft since there aren't tests yet.

Hello @tonyandrewmeyer, The interface is added under Telco table and tests are added. 
Could you please review  again ?

2024-04-18 10:54 UTC, tonyandrewmeyer approved these changes
Thanks for adding those! Looks great to me.

2024-04-18 12:13 UTC, gatici commented
> Thanks for adding those! Looks great to me.

Thank you @tonyandrewmeyer. Could you help me to merge it if everything seems fine ? Then, we can start to use it.

2024-04-18 13:44 UTC, merged