feat: adding fiveg_rfsim interface
canonical/charm-relation-interfaces pull request #175
Opened 2024-09-10 11:47 UTC by gatici

A new charm relation interface between the OAI NR UE and the OAI DU according to Spec: https://docs.google.com/document/d/1Tv3MHXcultURY5sI0zbOiNDo65li7p2GpXXdlnPebQE/edit

2024-10-01 15:49 UTC, ghislainbourgeois requested changes

2024-10-01 15:49 UTC, ghislainbourgeois commented on interfaces/fiveg_rfsim/v0/README.md
> +- Is expected to provide the DU's `rfsim` service address including pod ip and service port.
```suggestion
- Is expected to provide the DU's `rfsim` service ip.
```

2024-10-01 15:49 UTC, ghislainbourgeois commented on interfaces/fiveg_rfsim/v0/schema.py
> +        description="RF simulator service address which is equal to DU pod ip",
```suggestion
        description="RF simulator service IP",
```

2024-10-01 19:50 UTC, gatici commented on interfaces/fiveg_rfsim/v0/README.md
> +- Is expected to provide the DU's `rfsim` service address including pod ip and service port.
Thank you. Done.

2024-10-01 19:50 UTC, gatici commented on interfaces/fiveg_rfsim/v0/schema.py
> +        description="RF simulator service address which is equal to DU pod ip",
Done

2024-10-01 22:26 UTC, ghislainbourgeois approved these changes

2024-10-02 09:52 UTC, gatici commented
Hello @tonyandrewmeyer ,
I appreciate if you can review it.

2024-10-04 03:10 UTC, tonyandrewmeyer approved these changes
LGTM, thanks!

2024-10-07 06:21 UTC, gatici commented
@tonyandrewmeyer  Many thanks for the review. Can you merge it ? I do not have rights to do it.

2024-10-08 00:04 UTC, merged