Add hydra_endpoints relation interface
canonical/charm-relation-interfaces pull request #45
Opened 2023-02-17 12:29 UTC by natalian98

### Description
Kratos-operator requires `oauth2_provider` parameter in order to be able to interact with hydra-operator. This parameter is the Hydra's admin API endpoint, which will usually be exposed through Ingress using `traefik-k8s` charm. We aim to eliminate the need of manually passing config values to each charm and have them related instead.
To summarize this relation, Hydra needs to provide its endpoints to Kratos.

### Future work
The interface may be subject to change in case the future upstream releases of kratos and/or hydra require different parameters in order to integrate with each other.

2023-02-17 19:56 UTC, gruyaume requested changes

2023-02-17 19:56 UTC, gruyaume commented on interfaces/hydra_endpoints/v0/README.md
> +and requirer ([Ory Kratos](https://github.com/canonical/kratos-operator)) sides of relation.
Here I'd use the same as other relation interfaces: `This relation interface describes the expected behavior of charms claiming to be able to provide or consume an hydra endpoint`

2023-02-17 19:56 UTC, gruyaume commented on interfaces/hydra_endpoints/v0/README.md
> +Kratos requires `oauth2_provider` parameter in order to be able to interact with Hydra. This parameter is the Hydra's admin API endpoint,
This explanation is unnecessary here but can be in the PR description to add context

2023-02-17 19:56 UTC, gruyaume commented on interfaces/hydra_endpoints/v0/README.md
> +The purpose of this relation is to facilitate integration between the two charms by passing the endpoints from Hydra to Kratos.
This sentence seems also unnecessary here

2023-02-17 19:56 UTC, gruyaume commented on interfaces/hydra_endpoints/v0/README.md
> +For now, the only known requirer is Kratos and Hydra is the only provider, however the interface may be reused by other charms,
Again, not needed here

2023-02-17 19:56 UTC, gruyaume commented on interfaces/hydra_endpoints/v0/README.md
> +while the requirer will just consume the information.
`just consume` is too abstract

2023-02-17 19:56 UTC, gruyaume commented on interfaces/hydra_endpoints/v0/README.md
> +The provider must be able to supply admin and public endpoints. There are no criteria for the requirer as it's supposed to just consume the relation data.
I'd use the generic `Both the Requirer and the provider need to adhere to a certain set of criterias to be considered compatible with the interface.` and add details in the subbullets

2023-02-17 19:56 UTC, gruyaume commented on interfaces/hydra_endpoints/v0/README.md
> +- Is expected to send the public and admin URLs to the interface.
`send to the interface` is not really precise, `write to the application relation databag` seems more accurate

2023-02-17 19:56 UTC, gruyaume commented on interfaces/hydra_endpoints/v0/README.md
> +#### Example
There shouldn't be anything here as far as I understood the rest of the interface.

2023-02-17 19:56 UTC, gruyaume commented on interfaces/hydra_endpoints/v0/schemas/requirer.json
> +                "admin_endpoint": {
Those shouldn't be here, the requirer isn't writing data to the databag.

2023-02-20 09:10 UTC, nsklikas commented on interfaces/hydra_endpoints/v0/README.md
> +    > `http://[traefik-hostname]:[traefik-port]/[app-name]-[model-name]/`
The URL is not required to have this structure, this is true only if the user is using charmed traefik to access Hydra

2023-02-21 10:42 UTC, jnsgruk commented
This needs adding to the top-level README, but otherwise is starting to look good!

2023-02-21 10:42 UTC, jnsgruk commented on interfaces/hydra_endpoints/v0/README.md
> +}
Nit: something isn't right with the indentation here

2023-02-22 13:22 UTC, gruyaume commented on interfaces/hydra_endpoints/v0/README.md
> +- Is expected to consume the relation data.
This feels minimal, what should it do with those URL's

2023-02-22 13:22 UTC, gruyaume commented on interfaces/hydra_endpoints/v0/README.md
> +- Is expected to write the public and admin URLs to the application databag.
This feels minimal, the provider should probably serve something?

2023-02-22 13:22 UTC, gruyaume commented on interfaces/hydra_endpoints/v0/README.md
> +- There are no criteria for the requirer as it's supposed to just consume the relation data.
those 2 lines aren't necessary as the subbullets below will describe those same behaviors

2023-02-27 09:57 UTC, simskij requested changes

2023-02-27 09:57 UTC, simskij commented on interfaces/hydra_endpoints/v0/README.md
> +- Is expected to consume the relation data by updating its config file with the received endpoints.
```suggestion
- Is expected to consume the relation data to set up integration with Hydra.
```

2023-02-27 09:57 UTC, simskij commented on interfaces/hydra_endpoints/v0/README.md
> +## Usage
Please add a one-liner `## Overview` section above this one.

2023-02-27 12:55 UTC, gruyaume approved these changes

2023-02-27 13:15 UTC, simskij approved these changes

2023-02-27 13:28 UTC, jnsgruk commented
thanks @natalian98!

2023-02-27 13:29 UTC, merged