Rename mutual_tls to certificate_exchange
canonical/charm-relation-interfaces pull request #95
Opened 2023-08-14 15:35 UTC by ghislainbourgeois

Rename `mutual_tls` interface to `certificate_exchange`. Also bumps the API version to `v1` because of this change.

This removes the `mutual_tls` interface completely as it is getting deprecated. The new name is more general and is closer to the supported behaviour.

2023-08-14 16:32 UTC, sed-i approved these changes

2023-08-14 16:39 UTC, gruyaume approved these changes

2023-08-15 14:45 UTC, simskij requested changes
Exchange is almost equally bad as it's not really a two-way exchange, but a one-way transfer. How about `certificate_transfer`?

Because of the polarity of charm relations (one requirer, one provider - always), all charms that want to use this to exchange certs would have to provide both sides of the relation, so to me it would make more sense to make it clear that it's only one-way in the name as well.

2023-08-16 14:22 UTC, ghislainbourgeois commented
> 

@simskij Good point, I agree. I updated the name to `certificate-transfer` and also changed the version back to `v0`. It looks like Charmhub does not have support for renaming a library, so I will be creating a new one and deprecating the previous one.

2023-08-16 14:46 UTC, gruyaume commented
> > 
> 
> @simskij Good point, I agree. I updated the name to `certificate-transfer` and also changed the version back to `v0`. It looks like Charmhub does not have support for renaming a library, so I will be creating a new one and deprecating the previous one.

LGTM, please also update the PR name and overview content.

2023-08-18 13:43 UTC, simskij approved these changes

2023-08-18 13:43 UTC, merged